### ISSUE TITLE
wouldn't users impersonate people by altering current-user-id in chrome inspector?

### ISSUE THREAD

**Issue by la-ruby** [marcoroth/current.js#6]
in an application where user #1 is an admin user, wouldn't users be able to masquerade as him by opening up chrome inspector,

and chaging tag to

    <meta name="current-user-id" content="1">

**Comment by avioli** [comment]
I guess - only if your backend doesn't verify your token/cookie/whatever-you-use-to-authenticate and blindly trusts a user-alterable front-end value. :)

**Comment by marcoroth** [comment]
Hey @la-ruby, thanks for opening this issue!

The short answer is: no.

But it really depends how and what you implement in your application. Your backend should have to responsibility to check if the currently signed-in user is allowed to do a certain action.

Depending on how you use the library on the frontend, as user might be able to reveal an additional button on a page if it was tied to a specific user for example, but the action this button would call should again be verified by your backend. The backend is and should be the single-source-of-truth. 

The values you put in your <head> should always be treated as read-only values, the main motivation to put the values there is so that you can also easily read them in your JavaScript code.

I hope this helps!
